"""Internal SNI-DPC clustering implementation.

Generated from the immutable publication source by scripts/extract_core.py.
The extraction keeps the complete dependency closure of ``mng_dpc`` and omits
file loaders, plotting helpers, diagnostic printers, and the hard-coded demo.
Do not edit this file manually; update the extractor and rerun regression tests.
"""

import math
from collections import Counter, defaultdict, deque

import numpy as np
from sklearn.neighbors import KDTree

EPS = 1e-12


def component_shape_info(data, comp):
    idx = np.asarray(list(comp), dtype=int)
    if len(idx) <= 3:
        return {'thin_ratio': 1.0, 'axis': np.ones(data.shape[1], dtype=float), 'center': np.mean(data[idx], axis=0)}
    X = data[idx] - np.mean(data[idx], axis=0)
    try:
        (_, s, vt) = np.linalg.svd(X, full_matrices=False)
        if len(s) < 2 or s[0] <= EPS:
            thin_ratio = 0.0
        else:
            thin_ratio = float(s[1] / (s[0] + EPS))
        axis = vt[0]
        axis = axis / (np.linalg.norm(axis) + EPS)
    except Exception:
        thin_ratio = 1.0
        axis = np.ones(data.shape[1], dtype=float)
        axis = axis / (np.linalg.norm(axis) + EPS)
    return {'thin_ratio': thin_ratio, 'axis': axis, 'center': np.mean(data[idx], axis=0)}


def build_raw_to_cut_component_map(component_ids_raw, components_cut):
    raw_to_cut = {}
    for (cut_cid, comp) in enumerate(components_cut):
        raw_ids = [int(component_ids_raw[int(i)]) for i in comp]
        raw_cid = Counter(raw_ids).most_common(1)[0][0]
        if raw_cid not in raw_to_cut:
            raw_to_cut[raw_cid] = []
        raw_to_cut[raw_cid].append(cut_cid)
    return raw_to_cut


def min_inter_component_distance(data, comp_a, comp_b):
    idx_a = np.asarray(list(comp_a), dtype=int)
    idx_b = np.asarray(list(comp_b), dtype=int)
    if len(idx_a) == 0 or len(idx_b) == 0:
        return np.inf
    tree = KDTree(data[idx_b])
    (dist, _) = tree.query(data[idx_a], k=1)
    return float(np.min(dist))


def axis_similarity(axis_a, axis_b):
    axis_a = np.asarray(axis_a, dtype=float)
    axis_b = np.asarray(axis_b, dtype=float)
    return float(abs(np.dot(axis_a, axis_b)) / ((np.linalg.norm(axis_a) + EPS) * (np.linalg.norm(axis_b) + EPS)))


def compute_raw_component_center_caps_v94(data, components_raw, components_cut, component_ids_raw, ref_size, local_scale=None):
    """
    current 中心预算：

    1. raw component 仍然决定中心预算上限；
    2. 但不再只按 size / ref_size 给中心；
    3. 如果 raw component 是细长线型结构，则强制 cap = 1；
    4. 如果 raw component 只有一个显著 cut component，则 cap = 1；
    5. 很小且贴近同方向大线型 component 的 raw component，不单独给中心。
    """
    raw_to_cut = build_raw_to_cut_component_map(component_ids_raw, components_cut)
    raw_shapes = {}
    raw_center_caps = {}
    raw_parent = {}
    for cid in range(len(components_raw)):
        raw_parent[cid] = cid
        raw_shapes[cid] = component_shape_info(data, components_raw[cid])
    significant_cut_min = max(25.0, 0.5 * float(ref_size))
    for (raw_cid, comp) in enumerate(components_raw):
        size = len(comp)
        shape = raw_shapes[raw_cid]
        size_cap = int(round(size / (ref_size + EPS)))
        size_cap = max(1, size_cap)
        cut_ids = raw_to_cut.get(raw_cid, [])
        cut_sizes = [len(components_cut[cid]) for cid in cut_ids]
        significant_cut_count = sum((1 for s in cut_sizes if s >= significant_cut_min))
        significant_cut_count = max(1, significant_cut_count)
        cap = min(size_cap, significant_cut_count)
        if shape['thin_ratio'] <= 0.08 and size >= 1.2 * ref_size:
            cap = 1
        raw_center_caps[raw_cid] = cap
    main_raw_ids = [cid for (cid, comp) in enumerate(components_raw) if len(comp) >= 0.75 * ref_size]
    for (raw_cid, comp) in enumerate(components_raw):
        size = len(comp)
        if size >= 0.45 * ref_size:
            continue
        if len(main_raw_ids) == 0:
            continue
        best_parent = None
        best_dist = np.inf
        for pid in main_raw_ids:
            if pid == raw_cid:
                continue
            d = min_inter_component_distance(data, components_raw[raw_cid], components_raw[pid])
            if d < best_dist:
                best_dist = d
                best_parent = pid
        if best_parent is None:
            continue
        shape_small = raw_shapes[raw_cid]
        shape_big = raw_shapes[best_parent]
        same_axis = axis_similarity(shape_small['axis'], shape_big['axis']) >= 0.9
        both_line_like = shape_small['thin_ratio'] <= 0.12 and shape_big['thin_ratio'] <= 0.12
        if local_scale is not None:
            idx_small = np.asarray(list(comp), dtype=int)
            local_gap_scale = float(np.median(local_scale[idx_small]))
        else:
            local_gap_scale = 1.0
        near_parent = best_dist <= 3.5 * (local_gap_scale + EPS)
        if both_line_like and same_axis and near_parent:
            raw_center_caps[raw_cid] = 0
            raw_parent[raw_cid] = best_parent
    cap_info = {'raw_shapes': raw_shapes, 'raw_to_cut': raw_to_cut, 'raw_parent': raw_parent, 'significant_cut_min': significant_cut_min}
    return (raw_center_caps, cap_info)


def select_centers_by_raw_cut_budget(base_score, components_cut, component_ids_raw, components_raw, raw_center_caps):
    """
    v9.3 中心选择策略：

    1. raw component 决定最多几个中心；
    2. M_cc component 决定中心候选区域；
    3. 每个 raw component 内，优先从最大的 cut components 中选中心；
    4. 不让 tiny cut component 都变成中心。
    """
    raw_to_cut = build_raw_to_cut_component_map(component_ids_raw, components_cut)
    center_records = []
    for raw_cid in range(len(components_raw)):
        cut_ids = raw_to_cut.get(raw_cid, [])
        if len(cut_ids) == 0:
            continue
        cut_ids = sorted(cut_ids, key=lambda cid: len(components_cut[cid]), reverse=True)
        quota = int(raw_center_caps.get(raw_cid, 1))
        if quota == 0:
            continue
        quota = min(quota, len(cut_ids))
        for cut_cid in cut_ids[:quota]:
            idx = np.asarray(list(components_cut[cut_cid]), dtype=int)
            if len(idx) == 0:
                continue
            local_best = int(idx[np.argmax(base_score[idx])])
            center_records.append({'center': local_best, 'raw_cid': raw_cid, 'cut_cid': cut_cid, 'cut_size': len(idx), 'score': float(base_score[local_best])})
    center_records = sorted(center_records, key=lambda r: r['score'], reverse=True)
    centers = [r['center'] for r in center_records]
    return (centers, center_records)


def safe_set(values):
    return set((int(v) for v in values if v is not None))


def minmax_normalize(arr):
    arr = np.asarray(arr, dtype=float)
    (mn, mx) = (np.min(arr), np.max(arr))
    if abs(mx - mn) < EPS:
        return np.zeros_like(arr, dtype=float)
    return (arr - mn) / (mx - mn + EPS)


def euclidean_distance(data, i, j):
    return float(np.linalg.norm(data[i] - data[j]))


def structure_similarity_from_gamma(gamma, i, j, mode='scan'):
    """
    结构相似性。
    默认使用 SCAN 型结构相似性：|Γ_i ∩ Γ_j| / sqrt(|Γ_i||Γ_j|)。
    mode 参数内部固定默认，不在主流程中作为开关使用。
    """
    (gi, gj) = (gamma[i], gamma[j])
    if len(gi) == 0 or len(gj) == 0:
        return 0.0
    inter = len(gi & gj)
    if mode == 'jaccard':
        union = len(gi | gj)
        return inter / (union + EPS)
    return inter / (math.sqrt(len(gi) * len(gj)) + EPS)


def _query_knn_excluding_self(data, tree, k_neighbors):
    """查询每个点的前 k_neighbors 个近邻，不含自身。"""
    n = len(data)
    k_query = min(n, k_neighbors + 1)
    (distances, indices) = tree.query(data, k=k_query)
    knn_indices = []
    knn_distances = []
    for i in range(n):
        row_idx = []
        row_dist = []
        for (d, j) in zip(distances[i], indices[i]):
            j = int(j)
            if j == i:
                continue
            row_idx.append(j)
            row_dist.append(float(d))
            if len(row_idx) >= k_neighbors:
                break
        knn_indices.append(row_idx)
        knn_distances.append(row_dist)
    return (knn_indices, knn_distances)


def natural_neighbor_search(data):
    """
    最近自然邻居搜索。

    返回：
        r: 自然稳定轮次
        NN: 每个点主动选择的自然邻居集合 list[set]
        RNN: 每个点的逆邻居集合 list[set]
        nb: 每个点逆邻居数量 np.ndarray
        tree: KDTree
    """
    data = np.asarray(data, dtype=float)
    n = len(data)
    tree = KDTree(data)
    if n <= 1:
        return (0, [set() for _ in range(n)], [set() for _ in range(n)], np.zeros(n, dtype=int), tree)
    kmax = min(n - 1, max(8, int(math.sqrt(n) * 4)))
    (knn_indices, _) = _query_knn_excluding_self(data, tree, kmax)
    NN = [set() for _ in range(n)]
    RNN = [set() for _ in range(n)]
    zero_history = []
    r = 0
    while True:
        r += 1
        if r > kmax:
            if kmax >= n - 1:
                break
            kmax = min(n - 1, kmax * 2)
            (knn_indices, _) = _query_knn_excluding_self(data, tree, kmax)
        for i in range(n):
            if r - 1 < len(knn_indices[i]):
                j = int(knn_indices[i][r - 1])
                NN[i].add(j)
                RNN[j].add(i)
        nb = np.asarray([len(RNN[i]) for i in range(n)], dtype=int)
        zero_count = int(np.sum(nb == 0))
        if zero_count == 0:
            break
        zero_history.append(zero_count)
        if len(zero_history) >= 3 and zero_history[-1] == zero_history[-2] == zero_history[-3]:
            break
        if r >= n - 1:
            break
    nb = np.asarray([len(RNN[i]) for i in range(n)], dtype=int)
    return (r, NN, RNN, nb, tree)


def build_mng(NN, RNN):
    """
    构建多邻域图。

    M_i = NN_i ∪ RNN_i
    S_i = NN_i ∩ RNN_i，即严格自然邻居集合。
    Γ_i = {i} ∪ M_i，用于结构相似性。
    """
    n = len(NN)
    M = []
    S = []
    gamma = []
    for i in range(n):
        nn_i = safe_set(NN[i])
        rnn_i = safe_set(RNN[i])
        m_i = nn_i | rnn_i
        s_i = nn_i & rnn_i
        M.append(m_i)
        S.append(s_i)
        gamma.append(set([i]) | m_i)
    return (M, S, gamma)


def compute_reliability_from_nb(nb, eps=EPS):
    """
    根据逆邻居数量 nb 构造点可靠性权重。

    nb_i 越大，说明点 i 被更多点当作邻居，
    越像局部核心点，可靠性越高。

    reliability_i ∈ (0, 1]
    """
    nb = np.asarray(nb, dtype=float)
    nb_log = np.log1p(nb)
    max_v = np.max(nb_log)
    if max_v <= eps:
        return np.ones_like(nb_log)
    reliability = nb_log / (max_v + eps)
    reliability = np.maximum(reliability, eps)
    return reliability


def compute_local_scale_from_gamma(data, gamma, eps=EPS):
    """
    计算每个点的局部距离尺度 s_i。

    s_i = mean_{u in Gamma_i, u != i} d(i,u)

    作用：
    - 密集区域 s_i 小；
    - 稀疏区域 s_i 大；
    - 后续用 d_ij / sqrt(s_i*s_j) 做局部尺度归一化。
    """
    n = len(data)
    local_scale = np.zeros(n, dtype=float)
    all_scales = []
    for i in range(n):
        dists = []
        for u in gamma[i]:
            u = int(u)
            if u == i:
                continue
            d = euclidean_distance(data, i, u)
            if d > eps:
                dists.append(d)
        if len(dists) > 0:
            local_scale[i] = float(np.mean(dists))
            all_scales.append(local_scale[i])
        else:
            local_scale[i] = 0.0
    if len(all_scales) > 0:
        fallback = float(np.median(all_scales))
    else:
        fallback = 1.0
    fallback = max(fallback, eps)
    local_scale[local_scale <= eps] = fallback
    return local_scale


def weighted_common_neighbor_similarity(gamma_i, gamma_j, reliability, eps=EPS):
    """
    可靠共同邻居结构相似度。

    原始：
        sigma_ij = |Gamma_i ∩ Gamma_j| / sqrt(|Gamma_i| |Gamma_j|)

    改进：
        RCN_ij = sum_{u in common} w_u
                 / sqrt(sum_{u in Gamma_i} w_u * sum_{u in Gamma_j} w_u)
    """
    common = gamma_i & gamma_j
    if len(common) == 0:
        return 0.0
    common_weight = sum((reliability[int(u)] for u in common))
    weight_i = sum((reliability[int(u)] for u in gamma_i))
    weight_j = sum((reliability[int(u)] for u in gamma_j))
    return float(common_weight / (math.sqrt(weight_i * weight_j) + eps))


def adaptive_alpha(i, j, reliability, alpha_min=1.3, alpha_max=2.5):
    """
    自适应距离衰减指数。

    reliability 高：更像核心点，距离惩罚稍弱；
    reliability 低：更像边界点或噪声点，距离惩罚更强。
    """
    ri = reliability[int(i)]
    rj = reliability[int(j)]
    alpha_i = alpha_min + (1.0 - ri) * (alpha_max - alpha_min)
    alpha_j = alpha_min + (1.0 - rj) * (alpha_max - alpha_min)
    return float((alpha_i + alpha_j) / 2.0)


def compute_structure_similarity(M, gamma, reliability):
    """
    只对 MNG 中出现的边计算结构相似性。

    这里不再使用普通共同邻居数量，
    而是使用“可靠共同邻居加权结构相似度”。
    """
    sigma = {}
    n = len(M)
    for i in range(n):
        for j in M[i]:
            j = int(j)
            if i == j:
                continue
            key = (min(i, j), max(i, j))
            if key not in sigma:
                sigma[key] = weighted_common_neighbor_similarity(gamma[i], gamma[j], reliability)
    return sigma


def get_sigma(sigma, i, j):
    if i == j:
        return 1.0
    return float(sigma.get((min(i, j), max(i, j)), 0.0))


def compute_gravity(data, M, sigma, reliability, local_scale, beta=1.5, alpha_min=1.3, alpha_max=2.5):
    """Compute the screened interaction kernel on directed MNG edges.

    K_ij = sigma_ij**beta_ij * exp(-z_ij**2)
           / (z_ij + EPS)**alpha_ij,
    where z_ij is the distance scaled by the geometric mean of the two
    endpoint-local scales.  No separate excess-distance barrier is used.
    """
    n = len(data)
    G = {}
    G_norm = {}
    mean_G = np.zeros(n, dtype=float)
    for i in range(n):
        row_values = []
        for j in M[i]:
            j = int(j)
            if i == j:
                continue
            sij = get_sigma(sigma, i, j)
            if sij <= EPS:
                gij = 0.0
                G[i, j] = gij
                row_values.append(gij)
                continue
            dij = euclidean_distance(data, i, j)
            pair_scale = math.sqrt(local_scale[i] * local_scale[j]) + EPS
            d_scaled = dij / pair_scale
            alpha_ij = adaptive_alpha(i, j, reliability, alpha_min=alpha_min, alpha_max=alpha_max)
            wd = math.exp(-d_scaled ** 2)
            rel_ij = min(reliability[i], reliability[j])
            beta_local = beta + 0.3 + (1.0 - rel_ij) * 0.7
            gij = sij ** beta_local * wd / (d_scaled + EPS) ** alpha_ij
            G[i, j] = gij
            row_values.append(gij)
        if len(row_values) > 0:
            mean_G[i] = float(np.mean(row_values))
        else:
            mean_G[i] = 0.0
    for ((i, j), gij) in G.items():
        G_norm[i, j] = gij / (mean_G[i] + EPS)
    return (G, G_norm, mean_G)


def _distance_density(data, i, neighbors):
    neighbors = list(neighbors)
    if len(neighbors) == 0:
        return 0.0
    dist_sum = 0.0
    for j in neighbors:
        dist_sum += euclidean_distance(data, i, j)
    return len(neighbors) / (dist_sum + EPS)


def compute_composite_density(data, NN, RNN, M, S, G):
    """Combine three graph densities with a stable interaction density.

    The interaction term is log(1 + mean_j K_ij), avoiding the algebraic
    saturation caused by averaging row-normalized interactions.
    """
    n = len(data)
    rho_nn = np.zeros(n, dtype=float)
    rho_rnn = np.zeros(n, dtype=float)
    rho_snn = np.zeros(n, dtype=float)
    rho_g = np.zeros(n, dtype=float)
    for i in range(n):
        rho_nn[i] = _distance_density(data, i, NN[i])
        rho_rnn[i] = _distance_density(data, i, RNN[i])
        rho_snn[i] = _distance_density(data, i, S[i])
        if len(M[i]) > 0:
            raw_mean = np.mean([G.get((i, j), 0.0) for j in M[i]])
            rho_g[i] = math.log1p(raw_mean)
        else:
            rho_g[i] = 0.0
    rho = 0.2 * minmax_normalize(rho_nn) + 0.2 * minmax_normalize(rho_rnn) + 0.2 * minmax_normalize(rho_snn) + 0.4 * minmax_normalize(rho_g)
    detail = {'rho_nn': rho_nn, 'rho_rnn': rho_rnn, 'rho_snn': rho_snn, 'rho_g': rho_g, 'rho': rho}
    return (rho, detail)


def compute_dsngcap_density(data, tree, N):
    """
    DSNGCAP 密度：
        density_i = N / sum_{j in N_i} d_ij

    N 建议取：
        N = (r + max(nb)) // 2
    """
    data = np.asarray(data, dtype=float)
    n = len(data)
    N = int(max(1, min(N, n - 1)))
    density = np.zeros(n, dtype=float)
    for i in range(n):
        (dist, idx) = tree.query([data[i]], k=N + 1)
        dist_list = dist[0][1:]
        dist_sum = np.sum(dist_list)
        if dist_sum <= EPS:
            density[i] = 100000000.0
        else:
            density[i] = N / (dist_sum + EPS)
    return density


def compute_diff1_by_density(density):
    """
    对密度从小到大排序后，计算一阶差分。
    """
    sorted_density = np.sort(density)
    diff1 = []
    for i in range(len(sorted_density) - 1):
        diff1.append(sorted_density[i + 1] - sorted_density[i])
    return np.asarray(diff1, dtype=float)


def dsngcap_var_compute(diff1, scale):
    """
    将一阶差分 diff1 分成 scale 段，计算每一段的方差。
    """
    diff1 = list(diff1)
    if len(diff1) == 0:
        return np.asarray([0.0])
    diff1.append(diff1[-1])
    step = max(1, len(diff1) // scale)
    var = []
    for i in range(scale):
        start = i * step
        end = min((i + 1) * step, len(diff1))
        if start >= len(diff1):
            var.append(0.0)
        else:
            temp_diff1 = diff1[start:end]
            var.append(float(np.var(temp_diff1)))
    return np.asarray(var, dtype=float)


def dsngcap_get_alpha(var, scale):
    """
    DSNGCAP 的密度跳变点检测。
    返回低密度点比例 alpha，单位：百分比。
    """
    if len(var) == 0:
        return 0
    standard = scale // 2
    var = list(var[:standard])
    if len(var) == 0:
        return 0
    if max(var) <= EPS:
        return 0
    max_index = int(np.argmax(var))
    var_range = max(var) - var[-1]
    k = max(1, standard - max_index)
    over = []
    for i in range(1, k + 1):
        step_value = var_range / k * i
        p = 0
        for j in range(standard - 1, max_index - 1, -1):
            if step_value > var[j]:
                p += 1
            else:
                break
        over.append(p)
    if len(over) == 0:
        return 0
    enhance = []
    enhance.append(over[0])
    for i in range(1, len(over)):
        if over[i] == 0 or over[i - 1] == 0:
            enhance.append(1.0)
        else:
            enhance.append(over[i] / (over[i - 1] + EPS))
    a = int(np.argmax(enhance))
    alpha = standard - over[a]
    if max_index != 0:
        alpha -= 1
    alpha = max(0, alpha)
    if scale == 100:
        return int(alpha)
    else:
        return int(alpha * 10)


def detect_low_density_points_by_dsngcap_density(data, tree, r, nb):
    """
    直接采用 DSNGCAP 的密度跳变点去噪。
    不使用 Q，不使用原始置信度，不使用 rho * nb * mean_G。
    """
    n = len(data)
    if n <= 5:
        return (np.asarray([], dtype=int), np.arange(n), 0, None)
    N = int((r + int(np.max(nb))) // 2)
    N = max(1, min(N, n - 1))
    density = compute_dsngcap_density(data, tree, N)
    diff1 = compute_diff1_by_density(density)
    if n >= 500:
        scale = 100
    else:
        scale = 10
    var = dsngcap_var_compute(diff1, scale)
    alpha = dsngcap_get_alpha(var, scale)
    sorted_idx = np.argsort(density)
    low_len = int(n * alpha / 100)
    low_len = max(0, min(low_len, n - 1))
    low_indices = np.asarray(sorted_idx[:low_len], dtype=int)
    clean_indices = np.asarray(sorted_idx[low_len:], dtype=int)
    denoise_info = {'N': N, 'density': density, 'diff1': diff1, 'var': var, 'scale': scale, 'alpha': alpha}
    return (low_indices, clean_indices, alpha, denoise_info)


def detect_low_density_points_by_nb_adaptive(nb, r, eps=EPS):
    """
    Gravity 改进版：基于逆邻居数 nb 自适应去噪。

    核心思想（来自 Gravity 的 NoiseSeparate）：
        nb_i（逆邻居数）越低 → 越可能是噪声/离群点。

    改进：
        k 不再人工设定，而是根据 nb 的正值分布自动确定：
        k_auto = max(1, 15%分位数 of nb_positive)
        同时限制最多去除 30% 的点，防止过度去噪。
    """
    nb = np.asarray(nb, dtype=float)
    n = len(nb)
    if n <= 5:
        return (np.asarray([], dtype=int), np.arange(n), 0, {'k_auto': 0})
    nb_positive = nb[nb > eps]
    if len(nb_positive) > 0:
        k_auto = max(1, int(np.percentile(nb_positive, 15)))
    else:
        k_auto = 0
    noise_mask = nb <= k_auto
    low_indices = np.where(noise_mask)[0].astype(int)
    max_remove = int(n * 0.3)
    if len(low_indices) > max_remove:
        sorted_idx = np.argsort(nb)
        low_indices = sorted_idx[:max_remove].astype(int)
    clean_indices = np.setdiff1d(np.arange(n, dtype=int), low_indices).astype(int)
    alpha = int(round(len(low_indices) / n * 100))
    denoise_info = {'k_auto': k_auto, 'method': 'nb_adaptive'}
    return (low_indices, clean_indices, alpha, denoise_info)


def compute_low_confidence_score(rho, nb, mean_G):
    """
    Q_i = rho_i * (1 + nb_i) * (1 + mean_G_i)
    Q 越小越可能是低密度、低置信点。
    """
    rho_n = minmax_normalize(rho)
    nb_n = minmax_normalize(nb)
    g_n = minmax_normalize(mean_G)
    return rho_n * (1.0 + nb_n) * (1.0 + g_n)


def weak_connected_components(M):
    """
    将 MNG 有向图转成弱连通图，计算每个点所属连通分量。

    返回：
        component_ids: 每个点所属连通分量编号
        components: 每个连通分量包含的点集合
    """
    n = len(M)
    undirected = [set() for _ in range(n)]
    for i in range(n):
        for j in M[i]:
            j = int(j)
            if i == j:
                continue
            undirected[i].add(j)
            undirected[j].add(i)
    component_ids = np.full(n, -1, dtype=int)
    components = []
    comp_id = 0
    for start in range(n):
        if component_ids[start] != -1:
            continue
        q = deque([start])
        component_ids[start] = comp_id
        comp = set([start])
        while q:
            i = q.popleft()
            for j in undirected[i]:
                if component_ids[j] == -1:
                    component_ids[j] = comp_id
                    comp.add(j)
                    q.append(j)
        components.append(comp)
        comp_id += 1
    return (component_ids, components)


def robust_reference_component_size(components_cut):
    """
    从剪桥后的 M_cc components 中估计典型真实簇规模。

    思路：
    - M_cc 可能产生很多小碎片；
    - 小碎片不能参与典型簇大小估计；
    - 因此取 component size 的上半部分，再取中位数。
    """
    if len(components_cut) == 0:
        return 1.0
    sizes = np.asarray([len(c) for c in components_cut], dtype=float)
    if len(sizes) == 1:
        return max(float(sizes[0]), 1.0)
    q50 = float(np.percentile(sizes, 50))
    main_sizes = sizes[sizes >= q50]
    if len(main_sizes) == 0:
        main_sizes = sizes
    ref_size = float(np.median(main_sizes))
    return max(ref_size, 1.0)


def compute_component_delta(data, rho, component_ids):
    """
    不再计算依赖向量，只计算连通分量内的相对距离 delta。

    对每个点 i：
    1. 只在同一连通分量内寻找更高密度点；
    2. 如果 i 是本连通分量内最高密度点，则 delta 取该分量内最大距离；
    3. 不允许跨连通分量寻找依赖点。

    这样可以避免不同簇的重要高密度点互相连接。
    """
    n = len(data)
    delta = np.zeros(n, dtype=float)
    for i in range(n):
        comp_i = component_ids[i]
        same_comp = np.where(component_ids == comp_i)[0]
        higher = [j for j in same_comp if rho[j] > rho[i]]
        if len(higher) == 0:
            if len(same_comp) <= 1:
                delta[i] = 0.0
            else:
                dists = np.linalg.norm(data[same_comp] - data[i], axis=1)
                delta[i] = float(np.max(dists))
        else:
            dists = [euclidean_distance(data, i, int(j)) for j in higher]
            delta[i] = float(np.min(dists))
    return minmax_normalize(delta)


def compute_structural_reliability(M, S):
    """R_i = |S_i| / |M_i|。"""
    n = len(M)
    R = np.zeros(n, dtype=float)
    for i in range(n):
        R[i] = len(S[i]) / (len(M[i]) + EPS)
    return R


def prototype_force_to_point(data, gamma, rho, nb, G_norm, point_i, prototype, reliability=None, local_scale=None, sigma=None, beta=1.5, alpha_min=1.3, alpha_max=2.5):
    """
    点 i 到簇原型 P 的改进引力。

    如果 point_i -> j 在 G_norm 中存在，优先使用图上引力；
    如果不存在，则即时计算改进引力。

    同时加入原型距离权重，避免远距离高密度原型点吸走边界点。
    """
    prototype = list(prototype)
    if len(prototype) == 0:
        return 0.0
    dists = []
    for j in prototype:
        j = int(j)
        dists.append(euclidean_distance(data, point_i, j))
    dists = np.asarray(dists, dtype=float)
    if np.any(dists > EPS):
        proto_scale = float(np.median(dists[dists > EPS]))
    else:
        proto_scale = 1.0
    force = 0.0
    for (j, dij) in zip(prototype, dists):
        j = int(j)
        gij = G_norm.get((point_i, j), None)
        if gij is None:
            if reliability is not None and local_scale is not None and (sigma is not None):
                sij = get_sigma(sigma, point_i, j)
                if sij <= EPS:
                    gij = 0.0
                else:
                    pair_scale = math.sqrt(local_scale[point_i] * local_scale[j]) + EPS
                    d_scaled = dij / pair_scale
                    alpha_ij = adaptive_alpha(point_i, j, reliability, alpha_min=alpha_min, alpha_max=alpha_max)
                    wd = math.exp(-d_scaled ** 2)
                    rel_ij = min(reliability[point_i], reliability[j])
                    beta_local = beta + 0.3 + (1.0 - rel_ij) * 0.7
                    gij = sij ** beta_local * wd / (d_scaled + EPS) ** alpha_ij
            else:
                sij = structure_similarity_from_gamma(gamma, point_i, j)
                gij = sij / (dij * dij + EPS)
        proto_wd = math.exp(-(dij * dij) / (proto_scale * proto_scale + EPS))
        mass = rho[j] * (1.0 + nb[j])
        if reliability is not None:
            mass = mass * (1.0 + reliability[j])
        force += mass * gij * proto_wd
    return force / (math.sqrt(len(prototype)) + EPS)


def compute_center_score(rho, delta, nb, R, phi):
    """
    Score_i = rho_i * delta_i * (1+nb_i) * (1+R_i) * phi_i
    为避免 nb 量纲过强，内部使用归一化 nb。
    """
    nb_n = minmax_normalize(nb)
    score = rho * delta * (1.0 + nb_n) * (1.0 + R) * phi
    return score


def _scaled_edge_distance(data, local_scale, i, j):
    dij = euclidean_distance(data, i, j)
    return dij / (math.sqrt(local_scale[i] * local_scale[j]) + EPS)


def build_component_mng_by_strong_edges(data, M, S, G, local_scale):
    """
    只用于 weak connected components 的强边图。

    注意：
    - M 仍用于 Layer1/Layer2/Layer3 的候选搜索；
    - M_cc 只用于 component_ids；
    - 这样可以避免一两条弱桥边把多个真实簇合成一个 CC。
    """
    n = len(M)
    row_thr = np.full(n, np.inf, dtype=float)
    for i in range(n):
        vals = [G.get((i, int(j)), 0.0) for j in M[i] if G.get((i, int(j)), 0.0) > EPS]
        if len(vals) > 0:
            row_thr[i] = float(np.percentile(vals, 30))
    snn_dscaled = []
    for i in range(n):
        for j in S[i]:
            j = int(j)
            if i == j:
                continue
            snn_dscaled.append(_scaled_edge_distance(data, local_scale, i, j))
    if len(snn_dscaled) > 0:
        tau_mutual = float(np.percentile(snn_dscaled, 95))
        tau_strong = float(np.percentile(snn_dscaled, 85))
    else:
        tau_mutual = 1.8
        tau_strong = 1.5
    M_cc = [set() for _ in range(n)]
    for i in range(n):
        for j in M[i]:
            j = int(j)
            if i == j:
                continue
            d_scaled = _scaled_edge_distance(data, local_scale, i, j)
            raw_ij = G.get((i, j), 0.0)
            raw_ji = G.get((j, i), 0.0)
            mutual = j in S[i]
            keep_mutual = mutual and d_scaled <= tau_mutual and (max(raw_ij, raw_ji) >= min(row_thr[i], row_thr[j]))
            keep_strong = raw_ij >= row_thr[i] and raw_ji >= row_thr[j] and (d_scaled <= tau_strong)
            if keep_mutual or keep_strong:
                M_cc[i].add(j)
                M_cc[j].add(i)
    return M_cc


def layer1_core_expansion(center, labels, current_label, M, S, G_norm, rho, component_ids):
    """
    第一层：放宽后的簇核扩展。

    不再依赖 Dep(j)=i。
    从中心出发，在同一连通分量内扩展满足以下任一条件的点：

    1. 与当前 core 存在严格自然邻居关系；
    2. 与当前 core 的最大引力达到该点局部出边引力的较低阈值；
    3. 密度不低于该连通分量的低分位密度。

    目标：
        让第一层形成一个真正的簇核区域，而不是中心附近几个点。
    """
    n = len(M)
    center = int(center)
    comp_id = component_ids[center]
    comp_points = np.where(component_ids == comp_id)[0]
    rho_floor = np.percentile(rho[comp_points], 10)
    local_g_threshold = np.zeros(n, dtype=float)
    for i in range(n):
        vals = [G_norm.get((i, int(j)), 0.0) for j in M[i]]
        vals = [v for v in vals if v > 0]
        if len(vals) == 0:
            local_g_threshold[i] = 0.0
        else:
            local_g_threshold[i] = float(np.percentile(vals, 30))
    core = set([center])
    frontier = set([center])
    max_rounds = 4
    for _ in range(max_rounds):
        new_nodes = set()
        candidate_set = set()
        for u in frontier:
            candidate_set.update(M[u])
        for j in candidate_set:
            j = int(j)
            if component_ids[j] != comp_id:
                continue
            if labels[j] != -1 and labels[j] != current_label:
                continue
            if j in core:
                continue
            strict_hit = False
            for u in core:
                if j in S[u] or u in S[j]:
                    strict_hit = True
                    break
            g_to_core = 0.0
            for u in core:
                g_to_core = max(g_to_core, G_norm.get((j, u), 0.0), G_norm.get((u, j), 0.0))
            gravity_hit = g_to_core >= local_g_threshold[j]
            density_hit = rho[j] >= rho_floor
            if strict_hit or (gravity_hit and density_hit):
                new_nodes.add(j)
        if len(new_nodes) == 0:
            break
        core.update(new_nodes)
        frontier = new_nodes
    return core


def layer2_prototype_expansion(center, core, labels, current_label, data, rho, M, gamma, G_norm, component_ids):
    """
    第二层：放宽后的簇原型扩展。

    改动：
    1. 候选点从一阶邻域扩大到二阶邻域；
    2. 阈值从 mean 改为 25% 分位；
    3. 允许多轮扩展；
    4. 只限制在同一连通分量内，不跨分量。
    """
    center = int(center)
    comp_id = component_ids[center]
    prototype = set(core)
    max_rounds = 5
    for _ in range(max_rounds):
        candidate_set = set()
        for u in prototype:
            candidate_set.update(M[u])
        second_order = set()
        for u in candidate_set:
            second_order.update(M[int(u)])
        candidate_set.update(second_order)
        candidate_set = {int(v) for v in candidate_set if component_ids[int(v)] == comp_id and v not in prototype and (labels[int(v)] == -1 or labels[int(v)] == current_label)}
        if len(candidate_set) == 0:
            break
        gamma_proto = set()
        for u in prototype:
            gamma_proto.update(gamma[u])
        scores = {}
        for i in candidate_set:
            g_values = []
            for u in prototype:
                g_values.append(max(G_norm.get((i, u), 0.0), G_norm.get((u, i), 0.0)))
            g_values = np.asarray(g_values, dtype=float)
            g_max = float(np.max(g_values)) if len(g_values) > 0 else 0.0
            g_mean = float(np.mean(g_values)) if len(g_values) > 0 else 0.0
            inter = len(gamma[i] & gamma_proto)
            union = len(gamma[i] | gamma_proto)
            simi = inter / (union + EPS)
            density_ratio = rho[i] / (rho[center] + EPS)
            density_ratio = min(1.0, density_ratio)
            scores[i] = (0.45 * g_max + 0.35 * g_mean + 0.2 * simi) * (0.5 + 0.5 * density_ratio)
        if len(scores) == 0:
            break
        score_values = np.asarray(list(scores.values()), dtype=float)
        threshold = float(np.percentile(score_values, 25))
        new_nodes = {i for (i, s) in scores.items() if s >= threshold}
        if len(new_nodes) == 0:
            break
        old_size = len(prototype)
        prototype.update(new_nodes)
        if len(prototype) == old_size:
            break
    return prototype


def layer3_gravity_boundary_assignment(prototype, labels, current_label, prototypes, data, gamma, rho, nb, M, G_norm, component_ids, reliability=None, local_scale=None, sigma=None):
    """
    第三层：边界吸收层。

    只处理当前原型周围的一阶/二阶候选点；
    不再试图一次吃掉整个连通分量。
    剩余 clean 点交给后续 DPC 分配。
    """
    prototype = set(prototype)
    if len(prototype) == 0:
        return set()
    ref = next(iter(prototype))
    comp_id = component_ids[int(ref)]
    candidate_set = set()
    for u in prototype:
        candidate_set.update(M[int(u)])
    second_order = set()
    for u in candidate_set:
        second_order.update(M[int(u)])
    candidate_set.update(second_order)
    candidate_set = {int(i) for i in candidate_set if labels[int(i)] == -1 and component_ids[int(i)] == comp_id and (int(i) not in prototype)}
    if len(candidate_set) == 0:
        return set()
    same_comp_prototypes = []
    same_comp_proto_indices = []
    for (k, P) in enumerate(prototypes):
        if len(P) == 0:
            continue
        p_ref = next(iter(P))
        if component_ids[int(p_ref)] == comp_id:
            same_comp_prototypes.append(P)
            same_comp_proto_indices.append(k)
    all_prototypes = same_comp_prototypes + [set(prototype)]
    current_index = len(all_prototypes) - 1
    current_forces = []
    for i in candidate_set:
        f = prototype_force_to_point(data, gamma, rho, nb, G_norm, i, prototype, reliability=reliability, local_scale=local_scale, sigma=sigma)
        if f <= EPS:
            dmin = min((euclidean_distance(data, i, int(p)) for p in prototype))
            f = 1.0 / (dmin + EPS)
        current_forces.append(f)
    current_forces = np.asarray(current_forces, dtype=float)
    positive_forces = current_forces[current_forces > EPS]
    if len(positive_forces) == 0:
        return set()
    force_threshold = float(np.percentile(positive_forces, 5))
    layer3 = set()
    for i in candidate_set:
        forces = []
        for P in all_prototypes:
            f = prototype_force_to_point(data, gamma, rho, nb, G_norm, i, P, reliability=reliability, local_scale=local_scale, sigma=sigma)
            if f <= EPS:
                dmin = min((euclidean_distance(data, i, int(p)) for p in P))
                f = 1.0 / (dmin + EPS)
            forces.append(f)
        best_index = int(np.argmax(forces))
        if best_index != current_index:
            continue
        if forces[current_index] >= force_threshold:
            layer3.add(i)
    return layer3


def dpc_assign_remaining_clean_points_v94(data, labels, rho, component_ids_cut, component_ids_raw, raw_parent=None):
    labels = labels.copy()
    n = len(data)
    if raw_parent is None:
        raw_parent = {}
    order = np.argsort(-rho)
    for i in order:
        i = int(i)
        if labels[i] != -1:
            continue
        cut_i = int(component_ids_cut[i])
        raw_i = int(component_ids_raw[i])
        parent_i = int(raw_parent.get(raw_i, raw_i))
        same_cut = np.where(component_ids_cut == cut_i)[0]
        candidates = [int(j) for j in same_cut if rho[int(j)] > rho[i] and labels[int(j)] != -1]
        if len(candidates) > 0:
            nearest = min(candidates, key=lambda j: euclidean_distance(data, i, j))
            labels[i] = labels[nearest]
            continue
        same_cut_labeled = [int(j) for j in same_cut if labels[int(j)] != -1]
        if len(same_cut_labeled) > 0:
            nearest = min(same_cut_labeled, key=lambda j: euclidean_distance(data, i, j))
            labels[i] = labels[nearest]
            continue
        same_raw = np.where(component_ids_raw == raw_i)[0]
        same_raw_labeled = [int(j) for j in same_raw if labels[int(j)] != -1]
        if len(same_raw_labeled) > 0:
            nearest = min(same_raw_labeled, key=lambda j: euclidean_distance(data, i, j))
            labels[i] = labels[nearest]
            continue
        same_parent = np.where(component_ids_raw == parent_i)[0]
        same_parent_labeled = [int(j) for j in same_parent if labels[int(j)] != -1]
        if len(same_parent_labeled) > 0:
            nearest = min(same_parent_labeled, key=lambda j: euclidean_distance(data, i, j))
            labels[i] = labels[nearest]
            continue
        global_labeled = np.where(labels != -1)[0]
        if len(global_labeled) > 0:
            nearest = min(global_labeled, key=lambda j: euclidean_distance(data, i, int(j)))
            labels[i] = labels[nearest]
        else:
            labels[i] = 0
    return labels


def cluster_clean_data(clean_data):
    """
    在 clean 数据上执行 SNI-DPC 主过程。

    返回：
        labels: clean 数据标签，0,1,2,...；未分配点会在函数末尾分配
        prototypes: 每个簇的原型点集合，索引是 clean_data 内部索引
        info: 中间信息
    """
    n = len(clean_data)
    if n == 0:
        return (np.asarray([], dtype=int), [], {})
    (r, NN, RNN, nb, tree) = natural_neighbor_search(clean_data)
    (M, S, gamma) = build_mng(NN, RNN)
    reliability = compute_reliability_from_nb(nb)
    local_scale = compute_local_scale_from_gamma(clean_data, gamma)
    sigma = compute_structure_similarity(M, gamma, reliability)
    (G, G_norm, mean_G) = compute_gravity(clean_data, M, sigma, reliability, local_scale)
    (rho, rho_detail) = compute_composite_density(clean_data, NN, RNN, M, S, G)
    (component_ids_raw, components_raw) = weak_connected_components(M)
    M_cc = build_component_mng_by_strong_edges(clean_data, M, S, G, local_scale)
    (component_ids, components) = weak_connected_components(M_cc)
    ref_component_size = robust_reference_component_size(components)
    (raw_center_caps, raw_cap_info) = compute_raw_component_center_caps_v94(data=clean_data, components_raw=components_raw, components_cut=components, component_ids_raw=component_ids_raw, ref_size=ref_component_size, local_scale=local_scale)
    max_center_num = int(sum(raw_center_caps.values()))
    delta = compute_component_delta(clean_data, rho, component_ids)
    R = compute_structural_reliability(M, S)
    base_phi = np.ones(n, dtype=float)
    base_score = compute_center_score(rho, delta, nb, R, base_phi)
    (centers, center_records) = select_centers_by_raw_cut_budget(base_score=base_score, components_cut=components, component_ids_raw=component_ids_raw, components_raw=components_raw, raw_center_caps=raw_center_caps)
    raw_center_count = {cid: sum((1 for r in center_records if r['raw_cid'] == cid)) for cid in range(len(components_raw))}
    active_raw_components = [cid for (cid, cap) in raw_center_caps.items() if cap > 0]
    uncovered_raw_components = [cid for cid in active_raw_components if raw_center_count[cid] == 0]
    expandable_raw_components = [cid for cid in active_raw_components if raw_center_count[cid] < raw_center_caps[cid]]
    raw_to_cut = build_raw_to_cut_component_map(component_ids_raw, components)
    used_cut_ids = set((r['cut_cid'] for r in center_records))
    for raw_cid in uncovered_raw_components:
        cut_ids = sorted(raw_to_cut.get(raw_cid, []), key=lambda cid: len(components[cid]), reverse=True)
        for cut_cid in cut_ids:
            idx = np.asarray(list(components[cut_cid]), dtype=int)
            if len(idx) == 0:
                continue
            local_best = int(idx[np.argmax(base_score[idx])])
            center_records.append({'center': local_best, 'raw_cid': raw_cid, 'cut_cid': cut_cid, 'cut_size': len(idx), 'score': float(base_score[local_best])})
            used_cut_ids.add(cut_cid)
            raw_center_count[raw_cid] += 1
            break
    for raw_cid in expandable_raw_components:
        remain = raw_center_caps[raw_cid] - raw_center_count[raw_cid]
        if remain <= 0:
            continue
        cut_ids = sorted(raw_to_cut.get(raw_cid, []), key=lambda cid: len(components[cid]), reverse=True)
        for cut_cid in cut_ids:
            if cut_cid in used_cut_ids:
                continue
            idx = np.asarray(list(components[cut_cid]), dtype=int)
            if len(idx) == 0:
                continue
            local_best = int(idx[np.argmax(base_score[idx])])
            center_records.append({'center': local_best, 'raw_cid': raw_cid, 'cut_cid': cut_cid, 'cut_size': len(idx), 'score': float(base_score[local_best])})
            used_cut_ids.add(cut_cid)
            raw_center_count[raw_cid] += 1
            remain -= 1
            if remain <= 0:
                break
    centers = [r['center'] for r in center_records]
    labels = np.full(n, -1, dtype=int)
    prototypes = []
    clusters = []
    history = []
    for (lab, c) in enumerate(centers):
        labels[int(c)] = lab
    for (current_label, best_center) in enumerate(centers):
        best_center = int(best_center)
        core = layer1_core_expansion(best_center, labels, current_label, M, S, G_norm, rho, component_ids)
        if len(core) == 0:
            core = set([best_center])
        prototype = layer2_prototype_expansion(best_center, core, labels, current_label, clean_data, rho, M, gamma, G_norm, component_ids)
        cluster_points = set(prototype)
        for p in cluster_points:
            labels[int(p)] = current_label
        layer3 = layer3_gravity_boundary_assignment(prototype, labels, current_label, prototypes, clean_data, gamma, rho, nb, M, G_norm, component_ids, reliability=reliability, local_scale=local_scale, sigma=sigma)
        for p in layer3:
            labels[int(p)] = current_label
        cluster_points.update(layer3)
        prototypes.append(set(prototype))
        clusters.append(set(cluster_points))
        history.append({'center': int(best_center), 'core': set(core), 'prototype': set(prototype), 'layer3': set(layer3), 'cluster_points': set(cluster_points), 'center_record': center_records[current_label], 'labels_after': labels.copy()})
    labels = dpc_assign_remaining_clean_points_v94(data=clean_data, labels=labels, rho=rho, component_ids_cut=component_ids, component_ids_raw=component_ids_raw, raw_parent=raw_cap_info['raw_parent'])
    info = {'r': r, 'NN': NN, 'RNN': RNN, 'nb': nb, 'M': M, 'S': S, 'gamma': gamma, 'sigma': sigma, 'G_norm': G_norm, 'mean_G': mean_G, 'rho': rho, 'rho_detail': rho_detail, 'component_ids': component_ids, 'components': components, 'delta': delta, 'R': R, 'base_score': base_score, 'history': history, 'reliability': reliability, 'local_scale': local_scale, 'M_cc': M_cc, 'component_ids_raw': component_ids_raw, 'components_raw': components_raw, 'ref_component_size': ref_component_size, 'raw_center_caps': raw_center_caps, 'ref_component_size': ref_component_size, 'raw_center_caps': raw_center_caps, 'max_center_num': len(centers), 'raw_center_count': {cid: sum((1 for r in center_records if r['raw_cid'] == cid)) for cid in range(len(components_raw))}, 'raw_cap_info': raw_cap_info}
    return (labels.astype(int), prototypes, info)


def compute_original_graph_info(data):
    """原始数据上计算 MNG、密度、引力等，用于低密度点重分配。"""
    (r, NN, RNN, nb, tree) = natural_neighbor_search(data)
    (M, S, gamma) = build_mng(NN, RNN)
    reliability = compute_reliability_from_nb(nb)
    local_scale = compute_local_scale_from_gamma(data, gamma)
    sigma = compute_structure_similarity(M, gamma, reliability)
    (G, G_norm, mean_G) = compute_gravity(data, M, sigma, reliability, local_scale)
    (rho, rho_detail) = compute_composite_density(data, NN, RNN, M, S, G)
    Q = compute_low_confidence_score(rho, nb, mean_G)
    return {'r': r, 'NN': NN, 'RNN': RNN, 'nb': nb, 'M': M, 'S': S, 'gamma': gamma, 'sigma': sigma, 'G_norm': G_norm, 'mean_G': mean_G, 'rho': rho, 'rho_detail': rho_detail, 'Q': Q, 'tree': tree, 'reliability': reliability, 'local_scale': local_scale}


def redistribute_low_density_points(data, labels, low_indices, prototypes_original, original_info):
    """
    对低密度点做点对簇原型引力重分配。
    """
    gamma = original_info['gamma']
    rho = original_info['rho']
    nb = original_info['nb']
    G_norm = original_info['G_norm']
    reliability = original_info.get('reliability', None)
    local_scale = original_info.get('local_scale', None)
    sigma = original_info.get('sigma', None)
    if len(prototypes_original) == 0:
        return labels
    assigned_indices = np.where(labels != -1)[0]
    for i in low_indices:
        i = int(i)
        forces = [prototype_force_to_point(data, gamma, rho, nb, G_norm, i, P, reliability=reliability, local_scale=local_scale, sigma=sigma) for P in prototypes_original]
        if len(forces) > 0 and max(forces) > 0:
            labels[i] = int(np.argmax(forces))
        elif len(assigned_indices) == 0:
            labels[i] = 0
        else:
            nearest = min(assigned_indices, key=lambda j: euclidean_distance(data, i, int(j)))
            labels[i] = labels[nearest]
    return labels


def mng_dpc(data):
    """
    SNI-DPC 总流程。

    返回：
        labels: 原始数据标签
        info: 中间信息
    """
    data = np.asarray(data, dtype=float)
    n = len(data)
    if n == 0:
        return (np.asarray([], dtype=int), {})
    original_info = compute_original_graph_info(data)
    (low_ds, clean_ds, alpha_ds, denoise_ds) = detect_low_density_points_by_dsngcap_density(data=data, tree=original_info['tree'], r=original_info['r'], nb=original_info['nb'])
    (low_nb, clean_nb, alpha_nb, denoise_nb) = detect_low_density_points_by_nb_adaptive(nb=original_info['nb'], r=original_info['r'])
    low_indices = np.union1d(low_ds, low_nb).astype(int)
    clean_indices = np.setdiff1d(np.arange(n, dtype=int), low_indices).astype(int)
    alpha = int(round(len(low_indices) / n * 100))
    denoise_info = {'dsngcap': denoise_ds, 'nb_adaptive': denoise_nb, 'union_low_count': len(low_indices), 'dsngcap_only': len(np.setdiff1d(low_indices, low_nb)), 'nb_only': len(np.setdiff1d(low_nb, low_ds)), 'both': len(np.intersect1d(low_ds, low_nb))}
    clean_data = data[clean_indices]
    (clean_labels, clean_prototypes, clean_info) = cluster_clean_data(clean_data)
    labels = np.full(n, -1, dtype=int)
    for (local_i, original_i) in enumerate(clean_indices):
        labels[int(original_i)] = int(clean_labels[local_i])
    prototypes_original = []
    for P in clean_prototypes:
        prototypes_original.append(set((int(clean_indices[p]) for p in P)))
    labels = redistribute_low_density_points(data, labels, low_indices, prototypes_original, original_info)
    info = {'alpha': alpha, 'low_indices': low_indices, 'clean_indices': clean_indices, 'original_info': original_info, 'clean_info': clean_info, 'clean_labels': clean_labels, 'clean_prototypes': clean_prototypes, 'prototypes_original': prototypes_original, 'num_clusters': len(set(labels.tolist())) if len(labels) > 0 else 0, 'final_labels': labels.copy(), 'denoise_info': denoise_info}
    return (labels.astype(int), info)
