"""Regenerate the thread-safe public v10_0.65 core from frozen sources.

The v9.5 core remains an immutable historical dependency of the frozen v10
reference. The public module instead binds v10 functions in its own namespace,
so simultaneous estimator calls never patch process-global functions.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "src" / "sni_dpc" / "_core.py"
FROZEN = ROOT / "frozen" / "SNI_DPC_v10_0_65.py"
TARGET = ROOT / "src" / "sni_dpc" / "_core_v10.py"
BASE_SHA256 = "303e9fedb88122e3a6384522c3c6d2b7a21ee53c372720ff8478b3aeb8e37d71"
FROZEN_SHA256 = "153e3537cffef3c5754cc0dddc1a36b268d12a7605763cfe40f2da1dd02c8bca"
OVERRIDES = (
    "compute_composite_density",
    "compute_gravity",
    "prototype_force_to_point",
    "layer1_core_expansion",
    "layer2_prototype_expansion",
    "layer3_gravity_boundary_assignment",
)


def verified_source(path: Path, expected_hash: str) -> str:
    # Normalize Windows checkouts to the repository's canonical LF content.
    canonical = path.read_bytes().replace(b"\r\n", b"\n")
    actual = hashlib.sha256(canonical).hexdigest()
    if actual != expected_hash:
        raise RuntimeError(f"Unexpected source hash for {path}: {actual}")
    return canonical.decode("utf-8")


def render() -> str:
    base = verified_source(BASE, BASE_SHA256).replace("\r\n", "\n").rstrip()
    reference = verified_source(FROZEN, FROZEN_SHA256).replace("\r\n", "\n")
    tree = ast.parse(reference, filename=str(FROZEN))
    functions = {
        node.name: node for node in tree.body if isinstance(node, ast.FunctionDef)
    }
    missing = set(OVERRIDES) - set(functions)
    if missing:
        raise RuntimeError(f"Missing reference functions: {sorted(missing)}")
    body = []
    for name in OVERRIDES:
        source = ast.get_source_segment(reference, functions[name])
        if source is None:
            raise RuntimeError(f"Cannot extract {name}")
        source = re.sub(r"\bbase\.", "", source)
        if any(
            isinstance(node, ast.Name) and node.id == "base"
            for node in ast.walk(ast.parse(source))
        ):
            raise RuntimeError(f"Unbound reference to base in {name}")
        body.append(source)
    header = (
        "# Generated by scripts/build_v10_core.py from the immutable v9.5 core\n"
        "# and frozen SNI-DPC v10_0.65 reference. Do not edit this file manually.\n"
    )
    return header + base + "\n\n\n# v10_0.65 overrides; global lookups in mng_dpc resolve these definitions.\n\n" + "\n\n\n".join(body) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the generated core without writing")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("The generated v10_0.65 core is missing or out of date")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"{TARGET.relative_to(ROOT)}: sha256={hashlib.sha256(expected.encode('utf-8')).hexdigest()}")


if __name__ == "__main__":
    main()
