"""Extract the executable SNI-DPC clustering closure from the frozen source."""

from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "frozen" / "SNI_DPC_v9_5_publication.py"
TARGET = ROOT / "src" / "sni_dpc" / "_core.py"
ENTRYPOINT = "mng_dpc"


def called_functions(node: ast.AST, known: set[str]) -> set[str]:
    calls: set[str] = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Call) and isinstance(child.func, ast.Name):
            if child.func.id in known:
                calls.add(child.func.id)
    return calls


def dependency_closure(
    entrypoint: str,
    functions: dict[str, ast.FunctionDef],
) -> set[str]:
    required = {entrypoint}
    pending = [entrypoint]
    known = set(functions)

    while pending:
        name = pending.pop()
        for dependency in called_functions(functions[name], known):
            if dependency not in required:
                required.add(dependency)
                pending.append(dependency)

    return required


def main() -> None:
    tree = ast.parse(SOURCE.read_text(encoding="utf-8"), filename=str(SOURCE))
    functions = {
        node.name: node
        for node in tree.body
        if isinstance(node, ast.FunctionDef)
    }
    if ENTRYPOINT not in functions:
        raise RuntimeError(f"Missing entrypoint: {ENTRYPOINT}")

    required = dependency_closure(ENTRYPOINT, functions)
    ordered = sorted(
        (functions[name] for name in required),
        key=lambda node: node.lineno,
    )

    header = '''"""Internal SNI-DPC clustering implementation.

Generated from the immutable publication source by scripts/extract_core.py.
The extraction keeps the complete dependency closure of ``mng_dpc`` and omits
file loaders, plotting helpers, diagnostic printers, and the hard-coded demo.
Do not edit this file manually; update the extractor and rerun regression tests.
"""

import math
from collections import Counter, defaultdict, deque

import numpy as np
from sklearn.neighbors import KDTree

EPS = 1e-12
'''
    body = "\n\n\n".join(ast.unparse(node) for node in ordered)
    body = body.replace("MNG-DPC", "SNI-DPC").replace("v9.4", "current")
    TARGET.write_text(header + "\n\n" + body + "\n", encoding="utf-8")
    print(f"Extracted {len(ordered)} functions to {TARGET}")


if __name__ == "__main__":
    main()
